# Generated by Django 3.2.5 on 2021-07-28 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_profile_cga_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='cga_user',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fullnamemixin_ptr',
        ),
    ]
