# Generated by Django 3.2.5 on 2021-07-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210729_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dnd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='mature_content',
            field=models.BooleanField(default=True),
        ),
    ]
