# Generated by Django 3.2.5 on 2021-07-31 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210730_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='experiences',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.AddField(
            model_name='experiences',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='api.resume'),
        ),
        migrations.AddField(
            model_name='skills',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='api.resume'),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='api.user'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='api.user'),
        ),
    ]
