# Generated by Django 3.2.5 on 2021-07-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210731_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profession_headline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
