# Generated by Django 3.2.5 on 2021-08-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_profile_profession_headline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='freelance',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='full_time',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='voulnteer',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='availability',
            name='other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='status',
            field=models.IntegerField(choices=[(0, 'Full Time'), (1, 'Contract'), (2, 'Freelance'), (3, 'Voulnteer'), (4, 'Work Experience')], default=0),
        ),
    ]
