# Generated by Django 3.2.5 on 2021-08-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210803_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='artstation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='vimeo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
