# Generated by Django 3.2.5 on 2021-08-11 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_user_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='s3mediafiles',
            old_name='cga_file_type',
            new_name='file_type',
        ),
    ]
