# Generated by Django 3.2.5 on 2021-08-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_cga_file_type_s3mediafiles_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collabrators',
            name='title',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='collaborator',
            field=models.ManyToManyField(blank=True, related_name='artworkcollabrators', to='api.User'),
        ),
    ]
