# Generated by Django 3.2.5 on 2021-08-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_collabrators_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collabrators',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
