# Generated by Django 3.2.5 on 2021-08-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_collabrators_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collabrators',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
