# Generated by Django 3.2.5 on 2021-08-12 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_collabrators_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='tage_name',
            new_name='tag_name',
        ),
    ]
