# Generated by Django 3.2.5 on 2021-08-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20210812_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='is_2D',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='is_3D',
        ),
        migrations.AddField(
            model_name='artwork',
            name='artwork_type',
            field=models.IntegerField(choices=[(0, 'Is 2D'), (1, 'Is 3D')], default=0),
        ),
    ]
