# Generated by Django 3.2.5 on 2021-08-15 17:09

import api.model_utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20210815_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=api.model_utils.utils.get_resume_upload_path),
        ),
    ]
