# Generated by Django 3.2.5 on 2021-08-15 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_resume_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='resume',
            new_name='resume_file',
        ),
    ]
