# Generated by Django 3.2.5 on 2021-08-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_experiences_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
