# Generated by Django 3.2.5 on 2021-08-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_artwork_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fullnamemixin',
            old_name='first_name',
            new_name='a',
        ),
        migrations.RenameField(
            model_name='fullnamemixin',
            old_name='last_name',
            new_name='b',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
