# Generated by Django 3.2.5 on 2021-08-18 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20210818_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fullnamemixin_ptr',
        ),
    ]
