# Generated by Django 3.2.5 on 2021-08-18 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_user_fullnamemixin_ptr'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
