# Generated by Django 3.2.5 on 2021-08-29 07:35

import api.model_utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkcategory',
            name='category_image',
            field=models.FileField(blank=True, null=True, upload_to=api.model_utils.utils.get_upload_category),
        ),
    ]
