# Generated by Django 3.2.5 on 2021-08-29 07:40

import api.model_utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_artworkcategory_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwares',
            name='software_image',
            field=models.FileField(blank=True, null=True, upload_to=api.model_utils.utils.get_software_upload_path),
        ),
    ]
