# Generated by Django 3.2.5 on 2021-08-29 07:46

import api.model_utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_softwares_software_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=api.model_utils.utils.get_upload_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_banner',
            field=models.FileField(blank=True, null=True, upload_to=api.model_utils.utils.get_upload_path_banner),
        ),
    ]
