# Generated by Django 3.2.5 on 2021-09-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20210904_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Regular'), (2, 'Published'), (3, 'Admin')], default=1),
        ),
    ]
