# Generated by Django 3.2.5 on 2022-01-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_artwork_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Regular'), (2, 'Published'), (3, 'Admin'), (4, 'Moderator')], default=1),
        ),
    ]
