# Generated by Django 3.2.5 on 2022-01-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_artwork_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='serial',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Ten'), (11, 'Eleven'), (12, 'Twelve'), (13, 'Thirteen'), (14, 'Fourteen'), (15, 'Fifteen'), (16, 'Sixteen'), (17, 'Seventeen'), (18, 'Eighteen'), (19, 'Ninghteen'), (20, 'Twenty'), (21, 'Twentry One'), (22, 'Twenty Two'), (23, 'Twenty Three'), (24, 'Twenty Four'), (25, 'Twenty Five'), (26, 'Twenty Six'), (27, 'Twenty Seven'), (28, 'Twenty Eight'), (29, 'Twenty Nine'), (30, 'Thirty'), (31, 'Thirty One'), (32, 'Thirty Two'), (33, 'Thirty Three'), (100, 'Hundred')], default=100),
        ),
    ]
