# Generated by Django 3.2.5 on 2022-01-11 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_artwork_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='serial',
        ),
    ]
