# Generated by Django 3.2.5 on 2022-02-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_artwork_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s3mediafiles',
            name='is_reference_image',
        ),
        migrations.AddField(
            model_name='artwork',
            name='is_competition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='s3mediafiles',
            name='image_type',
            field=models.IntegerField(choices=[(1, 'Artwork'), (2, 'Refrence'), (3, 'Wip')], default=1),
        ),
    ]
