# Generated by Django 3.2.5 on 2022-05-02 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_alter_s3mediafiles_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='api.comments')),
                ('like', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='api.likes')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='api.user')),
            ],
            options={
                'db_table': 'notification',
            },
        ),
    ]
