# Generated by Django 3.2.5 on 2022-05-03 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreply',
            name='artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentreply', to='api.artwork'),
        ),
    ]
