# Generated by Django 3.2.5 on 2022-05-03 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_commentreply_artwork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreply',
            name='artwork',
        ),
    ]
