# Generated by Django 3.2.5 on 2022-05-20 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_notification_comment_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('competition_id', models.IntegerField()),
                ('competition_slug', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artwork', to='api.competitions'),
        ),
    ]
