# Generated by Django 3.2.5 on 2022-06-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_commentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='mention',
            field=models.IntegerField(blank=True, choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Ten')], null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='winner',
            field=models.IntegerField(blank=True, choices=[(1, 'One'), (2, 'Two'), (3, 'Three')], null=True),
        ),
    ]
